### ISSUE TITLE
Suppot Event API's

### ISSUE THREAD

**Issue by sreeise** [sreeise/graph-rs#249]
The event API covers multiple resources including users, groups, and calendars. Events can be done the same way that attachments are currently done by having its own module and linking to events from the different resources such as `groups("id").events()` or `users("id").events()`.

Calendar events reference: https://docs.microsoft.com/en-us/graph/api/group-list-events?view=graph-rest-1.0&tabs=http

Group events reference: https://docs.microsoft.com/en-us/graph/api/group-list-events?view=graph-rest-1.0&tabs=http

There is also Teams/TeamWork events but the Teams API has not been implemented yet.

**Comment by ec1oud** [comment]
https://docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&tabs=http

In calendar/request.rs you have     
`get!( list_events, Collection<serde_json::Value> => "calendars/events" );`
but it should be `calendar/events`, and then I get some JSON back with my own calendar events.

**Comment by sreeise** [comment]
> 
> 
> https://docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&tabs=http
> 
> In calendar/request.rs you have
> `get!( list_events, Collection<serde_json::Value> => "calendars/events" );`
> but it should be `calendar/events`, and then I get some JSON back with my own calendar events.

Thanks! I created an issue for it. Ill try to get it updated soon: https://github.com/sreeise/graph-rs/issues/262

**Comment by sreeise** [comment]
Fixed
