### ISSUE TITLE
graph-error fails to build due to unresolved imports

### ISSUE THREAD

**Issue by Zygimantass** [sreeise/graph-rs#255]
I don't know if this is maintained or not, and the error is weird since the commits seem to build fine in CI, but graph-error imports `from_as::FromToError` which does not seem to exist in the from_as library and the build fails. 

The last working commit seems to be ```3714d7e5875d9b55c2411d8e4dedef3bda95f434```.

Error:
```
error[E0432]: unresolved import `from_as::FromToError`
 --> graph-error/src/graph_failure.rs:3:5
  |
3 | use from_as::FromToError;
  |     ^^^^^^^^^-----------
  |     |        |
  |     |        help: a similar name exists in the module: `FromAsError`
  |     no `FromToError` in the root

error[E0119]: conflicting implementations of trait `std::convert::TryFrom<&mut reqwest::response::Response>` for type `graph_failure::GraphFailure`:
   --> graph-error/src/graph_failure.rs:254:1
    |
254 | impl TryFrom<&mut Response> for GraphFailure {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: conflicting implementation in crate `core`:
            - impl<T, U> std::convert::TryFrom<U> for T
              where U: std::convert::Into<T>;
```

**Comment by sreeise** [comment]
> I don't know if this is maintained or not, and the error is weird since the commits seem to build fine in CI, but graph-error imports `from_as::FromToError` which does not seem to exist in the from_as library and the build fails.
> 
> The last working commit seems to be `3714d7e5875d9b55c2411d8e4dedef3bda95f434`.
> 
> Error:
> 
> ```
> error[E0432]: unresolved import `from_as::FromToError`
>  --> graph-error/src/graph_failure.rs:3:5
>   |
> 3 | use from_as::FromToError;
>   |     ^^^^^^^^^-----------
>   |     |        |
>   |     |        help: a similar name exists in the module: `FromAsError`
>   |     no `FromToError` in the root
> 
> error[E0119]: conflicting implementations of trait `std::convert::TryFrom<&mut reqwest::response::Response>` for type `graph_failure::GraphFailure`:
>    --> graph-error/src/graph_failure.rs:254:1
>     |
> 254 | impl TryFrom<&mut Response> for GraphFailure {
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     |
>     = note: conflicting implementation in crate `core`:
>             - impl<T, U> std::convert::TryFrom<U> for T
>               where U: std::convert::Into<T>;
> ```

Sorry I did not see this. I put a few fixes in about a month ago that should have fixed this issue. If your still using it let me know if its working for you. 

And I try to do some work on it every so often. I have been pretty busy lately so its been difficult. I will update the README to reflect that as well.

**Comment by sreeise** [comment]
Going to close this as I believe it was fixed previously. The crate name was changed in graph_failure.rs: https://github.com/sreeise/graph-rs/blob/931baf1171a510a9b9c51a26a95f8f4a41b8060b/graph-error/src/graph_failure.rs#L4

 Reopen the issue if you believe its still happening.
