### ISSUE TITLE
PANIC: GraphDiscovery::Tenant().oauth() under Tokio

### ISSUE THREAD

**Issue by JRAndreassen** [sreeise/graph-rs#271]
If you run the following test:
```rust
    #[tokio::test(core_threads = 4)]
    async fn get_tennant_disco_tokio() {
        let oauth: GraphOAuth = 
            match GraphDiscovery::Tenant(TST_MSGRAPH_TENNANT.to_owned()).oauth()
            {
                Ok(tmpoauth) => tmpoauth,
                Err(err) => {
                    let msg = format!("[get_tennant_disco_tokio()]:, {:?}", err);
                    panic!(msg);
                },
            };
        println!("[get_tennant_disco_tokio()]:, {:?}", oauth);
    }

```

It fails in 
MicrosoftSigningKeysV2 = Commons::signing_keys :
> let client = reqwest::blocking::Client::builder().build()?;
------------------------^^^^^^-------
The Client is using the reqwest blocking client...
Is there a flag to force async / non-blocking ?

**Comment by sreeise** [comment]
@JRAndreassen Great question. The signing keys is actually one of the remaining things I need to add async for. Thanks for pointing this out. I added a ticket to get this done here: https://github.com/sreeise/graph-rs/issues/272

**Comment by JRAndreassen** [comment]
@sreeise ..

That s great... Thanks
If you could add an example on the correct way to get a token using "[client creds grant flow](// https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow)"
and issue a call all async...
That would be of tremendous help...

Thanks
  JR

**Comment by JRAndreassen** [comment]
The error: "invalid type: string \"3599\""
caused by 
```json
	"expires_in": "3599",
```

can be solved by:
```patch
diff --git a/graph-oauth/src/accesstoken.rs b/graph-oauth/src/accesstoken.rs
index 78276f67a8bbbacaba346f10f3bf097e16d18f39..dadd1ced5eb237a42b368cc8bf0f92f97923ec7a 100644
--- a/graph-oauth/src/accesstoken.rs
+++ b/graph-oauth/src/accesstoken.rs
@@ -50,6 +50,7 @@ use std::fmt;
 pub struct AccessToken {
     access_token: String,
     token_type: String,
+    #[serde(deserialize_with = "from_str")]
     expires_in: i64,
     scope: Option<String>,
     refresh_token: Option<String>,
@@ -61,6 +62,17 @@ pub struct AccessToken {
     jwt: Option<JsonWebToken>,
 }
 
+use std::str::FromStr;
+use serde::de::Deserialize;
+fn from_str<'de, T, D>(deserializer: D) -> Result<T, D::Error>
+    where T: FromStr,
+          T::Err: std::fmt::Display,
+          D: serde::de::Deserializer<'de>
+{
+    let s = String::deserialize(deserializer)?;
+    T::from_str(&s).map_err(serde::de::Error::custom)
+}
+
 impl AccessToken {
     pub fn new(token_type: &str, expires_in: i64, scope: &str, access_token: &str) -> AccessToken {
         let mut token = AccessToken {

```

**Comment by sreeise** [comment]
> The error: "invalid type: string "3599""
> caused by
> 
> ```json
> 	"expires_in": "3599",
> ```
> 
> can be solved by:
> 
> ```diff
> diff --git a/graph-oauth/src/accesstoken.rs b/graph-oauth/src/accesstoken.rs
> index 78276f67a8bbbacaba346f10f3bf097e16d18f39..dadd1ced5eb237a42b368cc8bf0f92f97923ec7a 100644
> --- a/graph-oauth/src/accesstoken.rs
> +++ b/graph-oauth/src/accesstoken.rs
> @@ -50,6 +50,7 @@ use std::fmt;
>  pub struct AccessToken {
>      access_token: String,
>      token_type: String,
> +    #[serde(deserialize_with = "from_str")]
>      expires_in: i64,
>      scope: Option<String>,
>      refresh_token: Option<String>,
> @@ -61,6 +62,17 @@ pub struct AccessToken {
>      jwt: Option<JsonWebToken>,
>  }
>  
> +use std::str::FromStr;
> +use serde::de::Deserialize;
> +fn from_str<'de, T, D>(deserializer: D) -> Result<T, D::Error>
> +    where T: FromStr,
> +          T::Err: std::fmt::Display,
> +          D: serde::de::Deserializer<'de>
> +{
> +    let s = String::deserialize(deserializer)?;
> +    T::from_str(&s).map_err(serde::de::Error::custom)
> +}
> +
>  impl AccessToken {
>      pub fn new(token_type: &str, expires_in: i64, scope: &str, access_token: &str) -> AccessToken {
>          let mut token = AccessToken {
> ```

Great catch! I will look at changing to this soon.

**Comment by sreeise** [comment]
> @sreeise ..
> 
> That s great... Thanks
> If you could add an example on the correct way to get a token using ["client creds grant flow"](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow)
> and issue a call all async...
> That would be of tremendous help...
> 
> Thanks
> JR
> 
> something like this:
> 
> ```rust
>     #[test]
>     fn get_calendars_sync() {
>         log_init();
>         let mut oauth  = GraphDiscovery::Tenant(TST_MSGRAPH_TENNANT.into())
>             .oauth()
>             .unwrap();        
>         let mut request = oauth
>             .client_id(TST_MSGRAPH_CLIENTID)
>             .client_secret(TST_MSGRAPH_CLIENTSEC)    
>             .build()
>             .client_credentials();            
>         println!("[get_calendars_sync]OAuth:, {:?}", oauth);
>         let access_token = 
>         match request.access_token().send() {
>             Ok(acctok) => acctok,
>             Err(err) => panic!("Error: {:?}", err),
>         };
>         let token = access_token.bearer_token();
>         if !token.is_empty()
>         {
>             let client = Graph::new(&token);
>             let cal_res = client.v1().me().calendar().get_default().send();
>             println!("[get_calendars_sync]Calendars returned:, {:?}", cal_res);
>         } else {
>             panic!("[get_calendars_sync]Failed to get token")            
>         }
>     }
> ```
> 
> This yeild:
> 
> ```
> [get_calendars_sync]OAuth:, OAuth { access_token: None, scopes: {}, credentials: 
> {	"access_token_url": "https://login.microsoftonline.com/TST_MSGRAPH_TENNANT/oauth2/token", 
> 	"authorization_url": "https://login.microsoftonline.com/TST_MSGRAPH_TENNANT/oauth2/authorize", 
> 	"client_id": "TST_MSGRAPH_CLIENTID", "client_secret": "TST_MSGRAPH_CLIENTSEC", 
> 	"logout_url": "https://login.microsoftonline.com/TST_MSGRAPH_TENNANT/oauth2/logout", 
> 	"refresh_token_url": "https://login.microsoftonline.com/TST_MSGRAPH_TENNANT/oauth2/token"} }
> thread 'sensor_msgraph::tests::get_calendars_sync' panicked at 
> 'Error: ReqwestError(reqwest::Error { kind: Decode, source: Error("invalid type: string \"3599\", expected i64", line: 1, column: 42) })', src\msgraph.rs:716:25
> ```
> 
> It would also be awesome, if the debug "{:?}" did not dump secrets...
> So it would output: "client_secret": "***Redacted**"

For the client credentials flow you need to do admin consent through the browser first before being able to get access tokens. The good thing is you only need to do that once and then afterward you can just get access tokens. The is an example here: https://github.com/sreeise/graph-rs/blob/master/examples/client_credentials.rs 

Basically you just need to set your client id, redirect uri, scopes, token url, and then set the authorization url to https://login.microsoftonline.com/common/adminconsent. After this do browser authorization using an admin login and then request an access token like normal.

**Comment by sreeise** [comment]
@JRAndreassen  The async methods have been added to the master branch. You can now do:

`GraphDiscovery::Tenant("TENANT").async_oauth()`

**Comment by JRAndreassen** [comment]
> @JRAndreassen The async methods have been added to the master branch. You can now do:
> 
> `GraphDiscovery::Tenant("TENANT").async_oauth()`

Sweet... Thanks :)

**Comment by JRAndreassen** [comment]
@sreeise ...
> I do have a question about whats causing this for you though. It looks like your going to get the access token and it fails because the response has expires_in as a String right, and the AccessToken struct is set to i64? I am just wondering why its failing for you. There are many tests that I use the OAuth crate for to get access tokens and dont see this issue currently.

After some serious head-banging, I figured out that the issues stem from using the 
discovery, which uses "https://login.microsoftonline.com/TENANTID/oauth2/authorize"
as opposed to "https://login.microsoftonline.com/TENANTID"

**Comment by sreeise** [comment]
> @sreeise ...
> 
> > I do have a question about whats causing this for you though. It looks like your going to get the access token and it fails because the response has expires_in as a String right, and the AccessToken struct is set to i64? I am just wondering why its failing for you. There are many tests that I use the OAuth crate for to get access tokens and dont see this issue currently.
> 
> After some serious head-banging, I figured out that the issues stem from using the
> discovery, which uses "https://login.microsoftonline.com/TENANTID/oauth2/authorize"
> as opposed to "https://login.microsoftonline.com/TENANTID"

Well head banging always seems to get the job done :+1: Let me know if you have any other issues that need to be looked at. I appreciate the feedback.

**Comment by JRAndreassen** [comment]
@sreeise 

This issue popped up again...
Not sure why...

I'm making a PR utilizing "serde_aux::deserialize_number_from_string"
 it will take either...
You OK with that ?

**Comment by sreeise** [comment]
> @sreeise
> 
> This issue popped up again...
> Not sure why...
> 
> I'm making a PR utilizing "serde_aux::deserialize_number_from_string"
> it will take either...
> You OK with that ?

Sure, as long as existing functionality works (also there might be some tests that need to be changed).

**Comment by sreeise** [comment]
Also, because some tokens do come in as a number your solution will need to account for whether it will be a `string` or an `i64`.

**Comment by JRAndreassen** [comment]
Hi...
PR: https://github.com/sreeise/graph-rs/pull/291/files
And serde_aux::deserialize_number_from_string should ...
(https://github.com/vityafx/serde-aux/blob/master/src/field_attributes.rs)
I tested, and included a test at the end of the file...
It can be moved to your tester dir..
(I usually put them at the end.
