### ISSUE TITLE
Dollar sign prefix ($) for query parameters

### ISSUE THREAD

**Issue by denkuy** [sreeise/graph-rs#320]
Filtering on the `/users` endpoint didn't work for me so in investigated - I found this piece in the documentation:

> On the beta endpoint, the $ prefix is optional. For example, instead of $filter, you can use filter. On the v1 endpoint, the $ prefix is optional for only a subset of APIs. For simplicity, always include $ if using the v1 endpoint.

(source https://docs.microsoft.com/en-us/graph/query-parameters)

## Reproduce Issue
```rust
let client = Graph::new(&std::env::var("TOKEN").unwrap());
let response = client
    .v1()
    .users()
    .list_user()
    .filter(&["userType eq 'guest'"])
    .send()
    .unwrap();

println!("{:#?}", response)
```

**Error (shortened)**
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ....
{
  url: "https://graph.microsoft.com/v1.0/users?filter=userType+eq+%27guest%27",
  status: 400,
  error: ErrorStatus { 
    code: Some("Request_BadRequest"),
    message: "Unrecognized query argument specified: 'filter'."
  ...
  }
}
```

## Test with $filter

Manually setting `$filter` works and returns the results as expected
```rust
let client = Graph::new(&std::env::var("TOKEN").unwrap());
    let response = client
        .v1()
        .users()
        .list_user()
        .query("$filter", "userType eq 'guest'")
        .send()
        .unwrap();

    println!("{:#?}", response)
```

---

I'm not sure if this should be introduced as a breaking change just in case...

**Comment by sreeise** [comment]
This is a great find. Not a big deal to change that for v1 endpoints only. Thanks for taking a look at this.
