### ISSUE TITLE
0.1.2 Regressions and breaking changes

### ISSUE THREAD

**Issue by DevLazio** [sreeise/graph-rs#328]
Hi,
thanks a lot for that release but unfortunately I found a few problems with it.

Regressions:
- it is no longer possible to execute multiple requests with the same async client. See https://gist.github.com/DevLazio/3afd1c221dd58b3949da9ced624aede3 for example. When updating to 0.1.2 I had to add line 37 to fix a deadlock.
- Errors are no longer Send + Sync

Breaking changes:
- deserializing to a struct with the json() method require encapsulating the type with GraphResponse<>
```  rust
let license_details: LicenseDetails = client
            .v1()
            .users()
            .id(user_id)
            .list_license_details()
            .json()
            .await?;

Ok(license_details.value)
```

became 
```rust 
  let license_details: GraphResponse<LicenseDetails> = client
            .v1()
            .users()
            .id(user_id)
            .list_license_details()
            .json()
            .await?;

  Ok(license_details.into_body().value)
```
and the documentation / readme should reflect that

**Comment by sreeise** [comment]
You are unable to run multiple requests with the same client? That is odd, the tests would have caught that easily so I am unsure whats causing it yet.

**Comment by sreeise** [comment]
The README definitely needs to be updated, which is something I intended to do already, but it slipped my mind.

**Comment by sreeise** [comment]
Can you tell me what dependencies and versions you are using in that gist? I am assume futures for the `stream::iter`, but I want to see if I can reproduce this.

**Comment by sreeise** [comment]
Also, the error that is returned did not change. It has always been

https://github.com/sreeise/graph-rs/blob/87380791b8e118f24326f1c86aa86ff094042441/graph-error/src/lib.rs#L19

Whether `Send + Sync` is required can depend on what you are doing. Some requests require that `Send + Sync` be upheld but it can depend. That is not to say that this issue is not happening. What could cause a type to lose its automatically derived `Send + Sync` is when it has added a member to itself that is not `Send + Sync`, and this may have happened when I moved the errors for uploads/downloads and added them to the enum GraphFailure error. Ill check into that. 

I have a feeling that what your experiencing with both the `Send + Sync` being missing and not being able to use the same client for multiple requests is due to the same issue. If the error type is no longer `Send + Sync` then there could be all kinds of issues with running async requests.

**Comment by sreeise** [comment]
Yeah so my theory about GraphFailure looks to be correct. Something happened to where Sync got unimplemnted. The previous version has

```rust
impl Sync for GraphFailure
```

and the new version has

```rust
impl !Sync for GraphFailure
```

https://docs.rs/graph-error/0.1.1/graph_error/enum.GraphFailure.html

**Comment by DevLazio** [comment]
Sorry if I came out rude, that was not my intent at all, what you are doing is awesome !

Relevant dependencies for my gist
``` toml
graph-rs-sdk = "0.1.2"
graph-http = "0.1.2"
serde = "1.0.130"
simple-error = "0.2.3"
tokio = { version = "1.15.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
futures = "0.3.19"
url = "2.2.2"
simplelog = { version = "^0.11.0", features = ["paris"] }
log = "0.4.14"
itertools = "0.10.1"
chrono = "0.4.19"
```

I am able to run multiple request with the same client, but not concurrently with buffered futures. The program deadlock as soon as the second request is being sent. I will try provide a full example today.

I will try to provide PR for updated docs and example too.

**Comment by DevLazio** [comment]
Here is a full example of the concurrency problem : https://github.com/DevLazio/graph-rs-concurrency-issue
You just need to replace the ACCESS_TOKEN.

**Comment by sreeise** [comment]
> Sorry if I came out rude, that was not my intent at all, what you are doing is awesome !
> 
> Relevant dependencies for my gist
> 
> ```toml
> graph-rs-sdk = "0.1.2"
> graph-http = "0.1.2"
> serde = "1.0.130"
> simple-error = "0.2.3"
> tokio = { version = "1.15.0", features = ["full"] }
> reqwest = { version = "0.11", features = ["json"] }
> futures = "0.3.19"
> url = "2.2.2"
> simplelog = { version = "^0.11.0", features = ["paris"] }
> log = "0.4.14"
> itertools = "0.10.1"
> chrono = "0.4.19"
> ```
> 
> I am able to run multiple request with the same client, but not concurrently with buffered futures. The program deadlock as soon as the second request is being sent. I will try to provide a full example today.
> 
> I will try to provide PR for updated docs and example too.

Nah, it was my fault, I was in a rush to get this out and couldnt really reproduce it so it was a little frustrating. Its always good to have a second set of eyes and even told that I missed something every now and then :smiling_face_with_tear: haha. Thank you for the example

**Comment by sreeise** [comment]
@DevLazio If you get a chance, can you look at https://github.com/sreeise/graph-rs/pull/329 and let me know if that fixes the issues your seeing? I was attempting to get the example to work on my end in a test but had to change up a few things and was getting some borrow issues so I figured you might be able to test this a bit better.

**Comment by DevLazio** [comment]
Unfortunately it doesn't fix the concurrency issue. 
It does fix the Send + Sync issue though.

**Comment by DevLazio** [comment]
I can reproduce the concurrency problem from this commit : 3dc2fb953d0b4932b1568083ebf390f68cbf44a3
No idea what caused it yet.

**Comment by DevLazio** [comment]
I found a solution :
Replacing
``` rust
    let response = self.client.response().await?;
```
with 
``` rust 
    let request = self.client.build().await;
    let response = request.send().await?;
```
in [graph-rs/graph-http/src/intoresponse.rs](https://github.com/sreeise/graph-rs/blob/master/graph-http/src/intoresponse.rs#L290) (the way it was before the fatal commit)

My theory is that with client.response() locks the client while the request is in fligh, preventing all other request from being fired and somewhere the second request acquire a lock needed for the first ?

Writing a test for this case could be tricky.

**Comment by sreeise** [comment]
> I found a solution : Replacing
> 
> ```rust
>     let response = self.client.response().await?;
> ```
> 
> with
> 
> ```rust
>     let request = self.client.build().await;
>     let response = request.send().await?;
> ```
> 
> in [graph-rs/graph-http/src/intoresponse.rs](https://github.com/sreeise/graph-rs/blob/master/graph-http/src/intoresponse.rs#L290) (the way it was before the fatal commit)
> 
> My theory is that with client.response() locks the client while the request is in fligh, preventing all other request from being fired and somewhere the second request acquire a lock needed for the first ?
> 
> Writing a test for this case could be tricky.

Nice find. Ill take a look at it and see what I can find.

**Comment by sreeise** [comment]
I think your right about how it acquires the lock. Because of the way both the async and non-async requests use the same macros via a trait in order to cut down on generated code, there is blocking happening on some of the calls that are made in graph-http, which was intentional but obviously there are consequences with every design decision. Because of that blocking, I believe that there may be a case here where the call to `response()` is acquiring a lock first, and then internally also calls `build()` which then requests to acquire a lock as well so we kind of end up blocking each other and this results in a dead lock.

**Comment by sreeise** [comment]
Merged changes and published a new version. Close this if you feel comfortable the issue is resolved and let me know if you see any other issues as well. Thanks!

**Comment by DevLazio** [comment]
Just tested the new version and everything works great.
Thanks a lot for everything : your work on this project, reactivity, communication, etc.
