### ISSUE TITLE
Handling of exotic endpoints

### ISSUE THREAD

**Issue by DevLazio** [sreeise/graph-rs#344]
Currently only the "https://graph.microsoft.com" ( either v1 or beta) is supported, but a few other exist :
- [https://graph.microsoft.us/ and https://dod-graph.microsoft.us/](https://devblogs.microsoft.com/microsoft365dev/new-microsoft-graph-endpoints-in-us-government-cloud/ ) for the Governement version of Azure
- [https://microsoftgraph.chinacloudapi.cn](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/o365-china-endpoints) for Office 365 operated by 21Vianet in China

And a few other are bound to happen some time in the futur : https://www.datacenterdynamics.com/en/news/orange-and-capgemini-launch-french-cloud-company-bleu-will-sell-microsoft-services-from-local-data-centers/

It may be hard in the futur to maintain exhaustivity of the list of endpoints (and their associated functions) so I suggest adding a "custom_endpoint" function to allow the user to specify the endpoint if it is not the standard one.

**Comment by sreeise** [comment]
Its a good idea. I like it. 👍
