### ISSUE TITLE
start delta requests from delta token

### ISSUE THREAD

**Issue by smndtrl** [sreeise/graph-rs#354]
Hi,

is there a way to request `/root/delta` starting from a delta token that is acquired beforehand?
As my Rust knowledge and experience is limited my assumptions may be wrong but I came up with the following ideas.

Add the delta token as parameter to the delta() function like in the official C# SDK. 
`var delta = await graphClient.Me.Drive.Root
	.Delta("1230919asd190410jlka")
	.Request()
	.GetAsync();`
which would lead to something similar
`let mut delta_recv =
        client.v1().drive(tok.drive_id).delta(tok.last_token).send().await;`

or

Add the token query parameter to the OData query parameters like `filter` or `select`.

Option 1 would be more inline with other SDK and the separation between what is OData and what is Graph API specific functionality. But meddling with codegen/macros is not something I feel comfortable with.

Option 2 is what I was able to do to get on with my learning project but consider not wise for API design reasons.

**Comment by sreeise** [comment]
Hey, yeah there isn't currently a way to do that but I like your first suggestion of doing it similar to the official C# SDK and having a way to use a previous delta token. Thats something I can take a look at doing when generating the clients or possibly adding in an extra method for those that is permanent and won't need codegen. Ill try to get back to you on this one soon.

**Comment by sreeise** [comment]
@smndtrl I opened a PR with some changes that add a query method and a client method for delta token. Also added an example to the examples directory for using them. The PR isn't finished yet. I only added a `delta_token` method for users, groups, and applications right now just so we could have a working example. Let me know if this is what your looking for and if it solves your problem. Ill still need to do a little bit of work on codegen and adding the remaining delta_token methods for the other api's that have a delta request if so, but wanted to get your feedback first.

https://github.com/sreeise/graph-rs/blob/8d07f1e27978bd3f2fb5b18b0fd9b81c256faef7/examples/delta_token.rs#L1-L61

**Comment by sreeise** [comment]
> Option 2 is what I was able to do to get on with my learning project but consider not wise for API design reasons.

Just wanted to ask, are you learning Rust for fun or is this school or work type project? 

> Option 1 would be more inline with other SDK and the separation between what is OData and what is Graph API specific functionality. But meddling with codegen/macros is not something I feel comfortable with.

Yeah I can understand that for sure. Macros in Rust are definitely one of the most useful features. But they can be overly complicated and learning how to use them and the nuances behind that is a challenge and may require a good bit of your time. At least for me, it was a long process of studying how to use them before I got the hang of them. If you do end up using Rust for more projects though I would highly recommend learning how to write them just for how practical they are.

**Comment by sreeise** [comment]
Closing this for now. Havnt heard back. Would rather get feedback first about this. Reopen if you feel its needed.

**Comment by smndtrl** [comment]
Hi,

finally had the time to revisit my Graph API project :)

I need the `delta` for keeping track of drive changes. There the API is atm still slightly different and not following the common OData way (`token vs $deltaToken`) but according to the docs it should change. For reference [the doc](https://docs.microsoft.com/en-us/graph/delta-query-overview#:~:text=*%20The%20usage%20pattern,listItem%3A%20delta.)

I wrapped everything so I can consume the changes as `Stream` and are happy now. From my side the approach also feels appropriate. I was wondering if a `delta(token: Option<String>)` would be nicer but that wouldn't fit as well to the OData style

**Comment by sreeise** [comment]
> I wrapped everything so I can consume the changes as `Stream` and are happy now. From my side the approach also feels appropriate. 

I am not exactly sure what you mean here. Are you saying you don't need this change then? 

> There the API is atm still slightly different and not following the common OData way (token vs $deltaToken) but according to [the doc](https://docs.microsoft.com/en-us/graph/delta-query-overview#:~:text=*%20The%20usage%20pattern,listItem%3A%20delta.)s it should change. For reference the doc

While the docs do say it should change in the future, I would stick for what they recommend for now as far as any changes go: `Resources in OneDrive and SharePoint also support this feature. For resources in OneDrive and SharePoint, append token=latest instead.` When they do update it we can look at it again.

**Comment by smndtrl** [comment]
> I am not exactly sure what you mean here. Are you saying you don't need this change then?

No, the change is exactly what I had in mind. I wanted to communicate that for my use case I created another abstraction to consume the delta (using your approach) as a `Stream` of items so it becomes possible to just `while let Some(item) = delta.next().await {}`
