### ISSUE TITLE
tokio-runtime-worker panicked...

### ISSUE THREAD

**Issue by kitplummer** [sreeise/graph-rs#373]
Following this, or any of the oauth examples like this one:

https://github.com/sreeise/graph-rs/blob/248f9298551e721042b7ee9a27e99ede3e5f0cce/examples/oauth_web_server_client_credentials.rs#L76

Results in: `thread 'tokio-runtime-worker' panicked at 'Cannot drop a runtime in a context where blocking is not allowed.`

Not Rust smart, so don't really know how to fix, or workaround.  Basic understanding is that the access_token request can't happen in the existing async process.  Any help?

**Comment by sreeise** [comment]
> Following this, or any of the oauth examples like this one:
> 
> https://github.com/sreeise/graph-rs/blob/248f9298551e721042b7ee9a27e99ede3e5f0cce/examples/oauth_web_server_client_credentials.rs#L76
> 
> Results in: `thread 'tokio-runtime-worker' panicked at 'Cannot drop a runtime in a context where blocking is not allowed.`
> 
> Not Rust smart, so don't really know how to fix, or workaround. Basic understanding is that the access_token request can't happen in the existing async process. Any help?

Hey, I believe the example there is accidentally using the non-async specific part of the client which won't work with an asynchronous runtime like tokio. You just need to switch to using the async part of the client.

The examples have changed over time so I apologize for that. The example of that method should be something like:

```rust
fn request_access_token() {
    let mut oauth = get_oauth_client();
    let mut request = oauth.build_async().client_credentials();
    let access_token = request.access_token().send().await.unwrap();

    println!("{:#?}", access_token);
    oauth.access_token(access_token);
}
```

**Comment by sreeise** [comment]
I created a ticket to get the examples updated. Thanks for pointing this out. https://github.com/sreeise/graph-rs/issues/374

**Comment by kitplummer** [comment]
A little bit more detail as well...I've been trying to figure out how to get the warp loop to shutdown after the oauth cycle(s) - because I'm building this into a `command-line-tool login` thinger.  I have been able to do the graceful shutdown with a tokio channel.  Once we get this async business sorted, I can add a PR with an example of the shutdown cycle, thinking it might be useful to others as well.

**Comment by sreeise** [comment]
> > You will probably have to use `.await` where the method is called as well: `request_access_token().await;`
> 
> Maybe this is just fair warning material, sorry I can't be of more direct help:
> 
> ```
> `await` is only allowed inside `async` functions and blocks
> only allowed inside `async` functions and blocks
> ```
> 
> This is referring to the function in the `let routes:` match block. I poked at it for a little bit, but couldn't make it happy.

The main function is already async.

https://github.com/sreeise/graph-rs/blob/248f9298551e721042b7ee9a27e99ede3e5f0cce/examples/oauth_web_server_client_credentials.rs#L23-L24

**Comment by sreeise** [comment]
> A little bit more detail as well...I've been trying to figure out how to get the warp loop to shutdown after the oauth cycle(s) - because I'm building this into a `command-line-tool login` thinger. I have been able to do the graceful shutdown with a tokio channel. Once we get this async business sorted, I can add a PR with an example of the shutdown cycle, thinking it might be useful to others as well.

Sure. Its not really something that I care too much about since this example is not meant to show how to use warp necessarily. But I dont mind making the example a little more complete if you want to open a PR.

**Comment by kitplummer** [comment]
> The main function is already async and this is where the request_access_token method is used.

Yep, agree with that.  But `rustc` doesn't - because it is actually called from the `.map()` function block.  Scope I suppose.

Appreciate the help!

**Comment by kitplummer** [comment]
I've been able to work around this...closing this one out.
