### ISSUE TITLE
AsyncAccessTokenGrant to access_token().send().await failing.

### ISSUE THREAD

**Issue by kitplummer** [sreeise/graph-rs#376]
Am sure it _is_ something I've misconfigured on my side.  That request is returning a 400.

If I use the code produced in the first bit (in a Postman POST) I can get the token.  Feeling sheepish - but can't seem to figure it out.  The GraphError isn't really pointing me to anything obvious.  Any ideas?

```
HERE2: AsyncAccessTokenGrant { oauth: AccessToken { access_token: "[REDACTED]", credentials: {"access_token_url": "https://login.microsoftonline.com/common/oauth2/v2.0/token", "authorization_url": "https://login.live.com/oauth20_authorize.srf?", "client_id": "[REDACTED]", "client_secret": "[REDACTED]", "code": "[REDACTED]", "redirect_uri": "http://localhost:8000/redirect"}, scopes: {"Tasks.ReadWrite"} }, grant: ClientCredentials }


ERROR: Graph error:
GraphError {
    headers: Some(
        GraphHeaders {
            url: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            status: 400,
            header_map: {
                "cache-control": "no-store, no-cache",
                "pragma": "no-cache",
                "content-type": "application/json; charset=utf-8",
                "expires": "-1",
                "strict-transport-security": "max-age=31536000; includeSubDomains",
                "x-content-type-options": "nosniff",
                "p3p": "CP=\"DSP CUR OTPi IND OTRi ONL FIN\"",
                "x-ms-request-id": "c666ee00-789f-4c30-be34-98bca041c302",
                "x-ms-ests-server": "2.1.13562.12 - SCUS ProdSlices",
                "x-xss-protection": "0",
                "set-cookie": "fpc=AgHJgu2OQbtMvKCHI2JCvY4; expires=Tue, 11-Oct-2022 18:20:36 GMT; path=/; secure; HttpOnly; SameSite=None",
                "set-cookie": "x-ms-gateway-slice=estsfd; path=/; secure; httponly",
                "set-cookie": "stsservicecookie=estsfd; path=/; secure; httponly",
                "date": "Sun, 11 Sep 2022 18:20:36 GMT",
                "content-length": "548",
            },
        },
    ),
    code: 400,
    error_message: ErrorMessage {
        error: None,
    },
}
```

**Comment by sreeise** [comment]
> Am sure it _is_ something I've misconfigured on my side. That request is returning a 400.
> 
> If I use the code produced in the first bit (in a Postman POST) I can get the token. Feeling sheepish - but can't seem to figure it out. The GraphError isn't really pointing me to anything obvious. Any ideas?
> 
> ```
> HERE2: AsyncAccessTokenGrant { oauth: AccessToken { access_token: "[REDACTED]", credentials: {"access_token_url": "https://login.microsoftonline.com/common/oauth2/v2.0/token", "authorization_url": "https://login.live.com/oauth20_authorize.srf?", "client_id": "[REDACTED]", "client_secret": "[REDACTED]", "code": "[REDACTED]", "redirect_uri": "http://localhost:8000/redirect"}, scopes: {"Tasks.ReadWrite"} }, grant: ClientCredentials }
> 
> 
> ERROR: Graph error:
> GraphError {
>     headers: Some(
>         GraphHeaders {
>             url: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
>             status: 400,
>             header_map: {
>                 "cache-control": "no-store, no-cache",
>                 "pragma": "no-cache",
>                 "content-type": "application/json; charset=utf-8",
>                 "expires": "-1",
>                 "strict-transport-security": "max-age=31536000; includeSubDomains",
>                 "x-content-type-options": "nosniff",
>                 "p3p": "CP=\"DSP CUR OTPi IND OTRi ONL FIN\"",
>                 "x-ms-request-id": "c666ee00-789f-4c30-be34-98bca041c302",
>                 "x-ms-ests-server": "2.1.13562.12 - SCUS ProdSlices",
>                 "x-xss-protection": "0",
>                 "set-cookie": "fpc=AgHJgu2OQbtMvKCHI2JCvY4; expires=Tue, 11-Oct-2022 18:20:36 GMT; path=/; secure; HttpOnly; SameSite=None",
>                 "set-cookie": "x-ms-gateway-slice=estsfd; path=/; secure; httponly",
>                 "set-cookie": "stsservicecookie=estsfd; path=/; secure; httponly",
>                 "date": "Sun, 11 Sep 2022 18:20:36 GMT",
>                 "content-length": "548",
>             },
>         },
>     ),
>     code: 400,
>     error_message: ErrorMessage {
>         error: None,
>     },
> }
> ```

There could be numerous reasons for this. Since its returning a 400 status code its most likely a configuration issue like you suggested. It looks like this is a client credentials grant that you are using and in those cases if you are attempting to log in as a user you must first give admin consent. This just means hitting the authorization endpoint, logging in as an admin when it prompts you, and accepting the terms that you are enabling the application to call the api on behalf of the user. This user is typically not the admin user but you still need to do the admin authorization. This only needs to be done one time and then you will be able to get access tokens for that user just using your application credentials. Every user you want to use a client credentials flow for must first go through admin authorization. 

So im not sure but you may be attempting to do the wrong authorization flow. You wont get a code in this type of authorization. 

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow

**Comment by kitplummer** [comment]
Here's my code:

```
#[tokio::main]
pub async fn login() -> Result<()> {
  println!("Loggin In");
    let (tx, mut rx) = tokio::sync::mpsc::unbounded_channel::<String>();
      // If this is not the first time you are using the client credentials grant
    // then you only have to run request_access_token() and you can comment out
    // what is below.
    let query = warp::query::<AccessCode>()
        .map(Some)
        .or_else(|_| async {
            Ok::<(Option<AccessCode>,), std::convert::Infallible>((None,))
        });

    let routes = warp::get().and(warp::path("redirect")).and(query).map(
        move |cc: Option<AccessCode>| match cc {
            Some(access_code) => {
                // Generic login page response.
                // Response::builder().body(String::from(
                //     "Successfully Logged In! You can close your browser.",
                // ))
                tx.send(access_code.code).unwrap();
                Ok(warp::reply::with_status("Hello from <b>tdi</b> - the access code was received and stored locally, you may safely close this browser window!", http::status::StatusCode::CREATED))
            }
            None =>  {
                tx.send("error getting access code".to_string()).unwrap();
                //Response::builder().body(String::from("There was an issue getting the access code."))
                Ok(warp::reply::with_status("Hello from <b>tdi</b> - error encountered requesting the access code.", http::status::StatusCode::NOT_FOUND))
            },
        },
    );

    // Get the oauth client and request a browser sign in
    let mut oauth = get_oauth_client();
    let mut request = oauth.build().code_flow();
    request.browser_authorization().open().unwrap();

    println!("Spawning server, awaiting access code.");
    let server = warp::serve(routes)
      .bind_with_graceful_shutdown(([127, 0, 0, 1], 8000),
                   async move { let code = rx.recv().await.unwrap(); req_access_token(code).await })
      .1;

    println!("waiting for result");
    server.await;

  Ok(())
}

fn get_oauth_client() -> OAuth {
    let mut oauth = OAuth::new();
    oauth
        .client_id(CLIENT_ID)
        .client_secret(CLIENT_SECRET)
        .add_scope("tasks.readwrite")
        .add_scope("user.read")
        .redirect_uri("http://localhost:8000/redirect")
        .authorize_url("https://login.microsoftonline.com/common/oauth2/v2.0/authorize")
        .access_token_url("https://login.microsoftonline.com/common/oauth2/v2.0/token")
        .refresh_token_url("https://login.microsoftonline.com/common/oauth2/v2.0/token");
    oauth
}

async fn req_access_token(code: String) {
    let mut oauth = get_oauth_client();
    // The response type is automatically set to token and the grant type is automatically
    // set to authorization_code if either of these were not previously set.
    // This is done here as an example.
    oauth.access_code(code.trim_end());
    
    let mut request = oauth.build_async().authorization_code_grant();
    println!("CODE: {:?}, AATG: {:#?}\n", code.trim_end(), request);

    match request.access_token().send().await {
      Ok(access_token) => {
        oauth.access_token(access_token);
        // If all went well here we can print out the OAuth config with the Access Token.
        println!("{:#?}", &oauth);
        // Save our configuration to a file so we can retrieve it from other requests.
        oauth
          .as_file("./.token")
          .unwrap();
      },
      Err(err) => {
        println!("{}", err);
        std::process::exit(1);
      }
    }
}
```

**Comment by kitplummer** [comment]
Stumped.  I can take the code that is retrieved, and generate a POST in Postman and get a token.  But this always gets 401 on the token request.

**Comment by kitplummer** [comment]
Bunch o' debugging and found that passing the CLIENT_SECRET into the token request causes the 401.  Not adding it to the oauth builder and everything works fine.

**Comment by sreeise** [comment]
I updated the OAuth examples and fixed the missing async issues there. Im going to close this bug/ticket as this is more of a discussion of using the oauth client. Feel free to create a discussion on this to continue talking about it.
