### ISSUE TITLE
Preserve raw JSON in case of error responses to retain every detail

### ISSUE THREAD

**Issue by moschroe** [sreeise/graph-rs#386]
I had difficulties debugging the right settings in the Azure AD backend and oauth setup and encountered an error similar to #376. Unfortunately, all I got was 400 `NoneError` which was, I'm sorry to say, quite useless. At the same time, the Content-Length of over 700 told me that there _had_ to be more information.

 I did check out `graph-rs`, added a `[patch.crates-io]` section for `graph-error` and patched the local checkout of `error.rs` like this:
```rust
#[async_trait]
impl WithGraphErrorAsync for reqwest::Response {
    async fn with_graph_error(self) -> Result<Self, GraphError> {
        let code = self.status();
        if code.is_client_error() || code.is_server_error() {
            let headers = Some(GraphHeaders::from(&self));
            // do not silently discard valuable information
            let response_raw: serde_json::Value = self.json().await.unwrap_or_else(|err| {
                serde_json::Value::String(format!("unable to parse response as JSON: {}", err))
            });
            let error_message = serde_json::from_value(response_raw.clone()).unwrap_or_default();
            Err(GraphError {
                headers,
                code,
                error_message,
                response_raw,
            })
        } else {
            Ok(self)
        }
    }
}
```
Same for the blocking code. Struct needs `Value` field and some constructors have to be adapted.

It would be a trivial addition that could be incredibly useful. The API responses are often very good at pointing out missing parameters, wrong scopes or other mistakes.

**Comment by sreeise** [comment]
Thanks for pointing this out. I thought we had cleaned up some of that missing info previously but it looks like this was missed. The main issue like you said is not being able to parse it in JSON so we need to just return the raw string. Feel free to open a PR with a fix if you want too. I labeled this as a bug so it will be higher priority but I always welcome PR's, especially if you have already looked into it and have a good fix.
