### ISSUE TITLE
Use async by default

### ISSUE THREAD

**Issue by sreeise** [sreeise/graph-rs#392]
### Discussed in https://github.com/sreeise/graph-rs/discussions/390

<div type='discussions-op-text'>

<sup>Originally posted by **sreeise** November 24, 2022</sup>
There are many ways in which the current setup makes it difficult to handle multiple use cases while still supporting both blocking and asynchronous requests. After research and working on this I have come to the conclusion the client should move to async by default and that the best way to handle this is by simplifying the client and making use of the `Clone` abilities of `Arc` ([std::sync::Arc](https://doc.rust-lang.org/std/sync/struct.Arc.html)). 
<br>
Using the reqwest crate we get the benefit of being able to clone using Arc without having to implement Arc ourselves. This is because reqwest handles the `Arc` wrapping of the client.
<br>
The first question is how would this work?
Here is an example of the client (naming not important here)
```rust
#[derive(Clone)]
pub struct Client {
    access_token: String,
    inner: reqwest::Client,
}

impl Client {
    // Build method to set defaults or customize the client such as connection timeout.
    pub fn build() -> Client {...}

}

// Simplified version 
pub struct GraphClient {
    http_client: Client
}
```

What we have is two clients. The first is the actual wrapper of reqwest::Client with the access token and the second is the graph client itself.
<br>
Basically we have our base GraphClient and that client will have methods to choose what api to call just as it does now. When the api is chosen, instead of taking a reference to the http client, we will clone the http client to an api client. That api client doesnt and will never care about the graph client. Each api client will be there own entities and can be created and called without the `GraphClient`.

Here is an example of the admin api client and what that would look like.
```rust
pub struct AdminClient {
  http_client: Client // Our http client fully owned
}

impl AdminClient {
  // Example only... I didnt look to see what the names now.
  pub fn get_admins(self) -> ResponseHandler {...} 
}
```

Lastly, each api call method will return a `ResponseHandler` (still working out the names). In general, the response handler will store a request or request builder but not the http client itself. This is because the response handler needs to or at least probably should act in a limited lifetime scope just as the request would before its called.

```rust
pub struct ResponseHandler {
  request_builder: RequestBuilder
}

impl ResponseHandler {
  pub async fn send(&self) -> Result<Response, Error> {...}
}
```

In addition to handling the request chain this way I am considering that most requests will just be returning a reqwest::Response instead of a wrapped response by default. This is because the response that reqwest returns can handle all of the use cases that are currently implemented. There will still be valid use cases that need to be be handled differently, such as downloading files or multi-part uploads, but those will be as a add on for convenience and not as a barrier or a wrapper. It will also allow using http response specific methods and data that are provided by the reqwest crate because its meant for that use case. There will still be conveniance methods but they will be more focused on providing additional functionality and not basic http functionality.
<br>
For blocking requests, I believe the best way to do it going forward would to use tokio, or possibly even a built in mechanism from the reqwest crate, to provide blocking on requests as an optional method call instead of the normal `send`.  I am still working on this and how it will work.

</div>

**Comment by sreeise** [comment]
This is going to be a major rewrite of some parts including the macros used. I have some work done on this that I will push soon.

**Comment by jnicholls** [comment]
I agree with this, it's better to default to async and wrap sync around it w/ a current thread executor (or just use `reqwest::blocking::Client` instead of `reqwest::Client` which does this for you, see its [wait module](https://docs.rs/reqwest/latest/src/reqwest/blocking/wait.rs.html#1-108) for details).

**Comment by sreeise** [comment]
> I agree with this, it's better to default to async and wrap sync around it w/ a current thread executor (or just use `reqwest::blocking::Client` instead of `reqwest::Client` which does this for you, see its [wait module](https://docs.rs/reqwest/latest/src/reqwest/blocking/wait.rs.html#1-108) for details).

Yep, just looking into this now. My changes for this don't have any blocking code or use of the blocking client in there yet. If I use the reqwest::blocking::Client I will probably have to duplicate parts of the code again which I rather not do. But I also just started looking into adding blocking just using the async client so I am not sure right now which route would be more clean right now.
