### ISSUE TITLE
Remove async-std dependency

### ISSUE THREAD

**Issue by jnicholls** [sreeise/graph-rs#397]
I noticed `async-std` is a dependency for this project, but the underlying HTTP client is `reqwest` which is strictly `tokio` based on top of `hyper`. I do not see `async_std` referenced anywhere in the project, so I believe this is an orphan dependency and can be removed so it is not brought into one's Cargo.lock dependency tree nor compiled.

**Comment by sreeise** [comment]
Your most likely right. For the life of me I cant remember what or why I put it there.

**Comment by sreeise** [comment]
I removed it from the main crate and published that change in 0.3.1. But I didn't realize that the graph-http crate had it also in its cargo file. I'll leave this issue up until that gets changed.

https://github.com/sreeise/graph-rs/blob/c6dafff68b2467f57ce90cc3beed7bfbd15f11f9/graph-http/Cargo.toml#L11
